test-job1:
  stage: test
  image: python:3.10
  before_script:
    - pip3 install -e .[dev]
  script:
    - coverage run -m pytest --junitxml=junit.xml
  after_script:
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: junit.xml
  allow_failure: true
